### ISSUE TITLE
graphical output

### ISSUE THREAD

**Issue by mobilome** [AshokHub/xmlBLASTparser#1]
hi
Is it possible to add a graphical output？like locBLAST？

**Comment by AshokHub** [comment]
Yes. Actually, the layout of locBLAST was derived from xmlBLASTparser.

**Comment by mobilome** [comment]
> Yes. Actually, the layout of locBLAST was derived from xmlBLASTparser.

But it doesn't look the same as locblast. It lacks graphical output and save buttons. 
If I want it to output the same layout as locblast, what do I need to do?

**Comment by AshokHub** [comment]
Currently I am focusing on improving  locBLAST, so I have not updated xmlBLASTparser.

**Comment by mobilome** [comment]
> Currently I am focusing on improving locBLAST, so I have not updated xmlBLASTparser.

Ok, I get it now, thanks！
